AdminSystem/AddressBookConfirmDelete.aspx, AdminSystem/AddressBookViewer.aspx, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsStock.cs, Testing6/TestingStock.csproj, Testing6/tstStock.cs
Practical 6 Completed created clsStock class under class library and tstStock class
=> Practical 6 Completed

ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsOrders.cs, Testing1/TestingAddressBook.csproj, Testing4/TestingOrders.csproj, Testing4/tstOrders.cs
=> Adding testing for orders class

Testing3/TestingEvents.csproj, Testing3/clsEvents.cs, Testing3/tstEvents.cs
=> Adding tests for events class

ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsCustomers.cs, Testing2/TestingCustomers.csproj, Testing2/tstCustomers.cs
=> Adding testing for customers class

ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
Everything is OK and looks fine
=> Added another method onto the tstOrders class

Testing4/tstOrders.cs
=> Added further testing into orders class

ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
=> Added new testing for the orders class

ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
=> Modified the clsOrders and tstOrder class, adding several working tests

AdminSystem/OrdersDataEntry.aspx.cs, ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
=> Updated the order class, tests, and ASPX page

ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsEvents.cs, Testing3/TestingEvents.csproj, Testing3/clsEvents.cs, Testing3/tstEvents.cs
=> lab 7 is done!!!! All Test Passed!

ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
Everything is OK and fully functional
=> Updated test and class code for additional test and find methods

AdminSystem/StockDataEntry.aspx, AdminSystem/StockDataEntry.aspx.cs, AdminSystem/StockViewer.aspx.cs
=> lab 8 completed

ClassLibrary/clsCustomers.cs, Testing2/tstCustomers.cs
Everything is OK and working - tested by Uthman
=> Lab 7 completed

AdminSystem/OrdersDataEntry.aspx, AdminSystem/OrdersDataEntry.aspx.cs, ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
Everything is OK and successfully working
=> Implemented tests, find method, and error handling for the orders class

AdminSystem/OrdersDataEntry.aspx, AdminSystem/OrdersDataEntry.aspx.cs, AdminSystem/OrdersViewer.aspx.cs, Testing4/tstOrders.cs
=> Updated code and tests for order form and error handling.

AdminSystem/StockDataEntry.aspx.cs, AdminSystem/StockList.aspx, AdminSystem/StockList.aspx.cs, ClassLibrary/clsStock.cs, ClassLibrary/clsStockCollection.cs, Testing6/tstStockCollection.cs
=> lab 13a completed

ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
=> Lab 10 has been completed

AdminSystem/OrdersDataEntry.aspx.cs
=> Fixed type conversion issues in DataEntry page code

AdminSystem/StockDataEntry.aspx.cs, AdminSystem/StockList.aspx, AdminSystem/StockList.aspx.cs, ClassLibrary/clsStockCollection.cs, Testing6/tstStockCollection.cs
=> lab 13b completed with update method

AdminSystem/OrdersList.aspx, AdminSystem/OrdersList.aspx.cs, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsOrdersCollection.cs, Testing4/TestingOrders.csproj, Testing4/tstOrdersCollection.cs
=> Revised unit tests, fixed issues, updated classes, added methods.

AdminSystem/OrdersDataEntry.aspx.cs, AdminSystem/OrdersList.aspx, AdminSystem/OrdersList.aspx.cs, ClassLibrary/clsOrdersCollection.cs, Testing4/tstOrdersCollection.cs
=> Updated event handler to add orders to database.

AdminSystem/OrdersDataEntry.aspx.cs, AdminSystem/OrdersList.aspx, AdminSystem/OrdersList.aspx.cs, ClassLibrary/clsOrdersCollection.cs, Testing4/tstOrdersCollection.cs
=> Implemented add, update methods for order data entry functionality.

AdminSystem/OrdersConfirmDelete.aspx, AdminSystem/OrdersConfirmDelete.aspx.cs, AdminSystem/OrdersDataEntry.aspx.cs, AdminSystem/OrdersList.aspx, AdminSystem/OrdersList.aspx.cs, ClassLibrary/clsOrdersCollection.cs, Testing4/tstOrdersCollection.cs
=> Implemented add, edit and delete functionalities within the order classes

ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsStaff.cs, Testing5/TestingStaff.csproj, Testing5/tstStaff.cs
completed lab 6 in this version
=> Steves branch

AdminSystem/OrdersDataEntry.aspx, AdminSystem/OrdersDataEntry.aspx.cs, AdminSystem/OrdersList.aspx.cs, AdminSystem/OrdersViewer.aspx.cs, ClassLibrary/clsOrders.cs, ClassLibrary/clsOrdersCollection.cs, Testing4/tstOrders.cs, Testing4/tstOrdersCollection.cs
ammaar is the goat he gets free hotville
=> ammaar has changed uthmans code i take the credit

AdminSystem/EventsDataEntry.aspx, AdminSystem/EventsDataEntry.aspx.cs, ClassLibrary/clsEvents.cs
=> Lab 11 done

AdminSystem/EventsList.aspx, AdminSystem/EventsList.aspx.cs, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsEventsCollection.cs, Testing3/TestingEvents.csproj, Testing3/tstEventsCollection.cs
=> lab  12 done !!!

ClassLibrary/clsOrdersCollection.cs, ClassLibrary/clsStaff.cs, Testing4/tstOrdersCollection.cs
=> Added further test classes and updating methods

AdminSystem/OrdersList.aspx, AdminSystem/OrdersList.aspx.cs, ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
=> Fixed validation and tests for character length constraints.

AdminSystem/OrdersList.aspx, AdminSystem/OrdersList.aspx.cs, AdminSystem/OrdersStatistics.aspx, AdminSystem/OrdersStatistics.aspx.cs, ClassLibrary/clsOrders.cs, Testing4/TestingOrders.csproj, Testing4/tstOrders.cs
Everything is OK and fully working.
=> Added statistics feature and implemented redirection functionality.

AdminSystem/OrdersDataEntry.aspx, AdminSystem/OrdersDataEntry.aspx.cs, AdminSystem/OrdersList.aspx, AdminSystem/OrdersList.aspx.cs, AdminSystem/TeamMainMenu.aspx, AdminSystem/TeamMainMenu.aspx.cs
Every practical handout has been completed and everything is working as expected.
=> Finished Lab 16

ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
=> Modified and added further validation tests

Testing4/tstOrders.cs
=> Fixed minor bugs

ClassLibrary/clsOrders.cs, Testing4/tstOrders.cs
=> Additional minor bug fixes

AdminSystem/EventsDataEntry.aspx.cs, AdminSystem/EventsList.aspx, AdminSystem/EventsList.aspx.cs, ClassLibrary/clsEventsCollection.cs, Testing3/tstEventsCollection.cs
=> lab13b done!!!

AdminSystem/EventsConfirmDelete.aspx, AdminSystem/EventsConfirmDelete.aspx.cs, AdminSystem/EventsList.aspx, AdminSystem/EventsList.aspx.cs, ClassLibrary/clsEventsCollection.cs, Testing3/tstEventsCollection.cs
=> 14a and 14b done!!!

AdminSystem/TeamMainMenu.aspx, AdminSystem/TeamMainMenu.aspx.cs, Testing4/tstOrders.cs
=> Minor Bug Fixed v3
